AccessibilityGenerator: Update gem declaration (#1185)
In order to avoid the following failure in CI, we need to load the
latest build (not release) of capybara_accessibility_audit.

```
NoMethodError: undefined method `configure' for module RSpec (NoMethodError)

      RSpec.configure do |config|
```

For reference, [this commit][] fixes the issue.

[this commit]: https://github.com/thoughtbot/capybara_accessibility_audit/commit/0ee6922ef19a391fb617778ef730af30b2680759